const strings = {
  access: {
    token: 'jmvhDdDBMvqb=M@6h&QVA7x'
  },
  ReceivingMaterials: 'receivingmaterials',
  Attachments: 'Attachments',
  ProductionOrder: 'ProductionOrder',
  MaterialGoods: 'MaterialGoods',
  FeedStockType: 'FeedStockType',
  BalesPressing: 'balespressings',
  GenerateNumber: 'GenerateNumber',
  MasterGoodsCart: 'MasterGoodsCart',
  ProductionOrderCart: 'ProductionOrderCart',
  DeliveryOrder: 'DeliveryOrder',
  Users: 'users',
  Auth: 'Auth',
  District: 'districts',
  Regency: 'regencies',
  Province: 'provinces',
  Village: 'villages',
  Department: 'Department',
  Job: 'Job',
  Job_level: 'Job_level',
  Role_user: 'Role_user',
  Uom: 'Uom',
  PurchaseOrder: 'PurchaseOrder',
  SalesOrder: 'SalesOrder',
  TransactionCart: 'TransactionCart',
  code: {
    Receiving: 'RM',
    ReceivingBales: 'RB',
    BalesPress: 'BP',
    DeliveryOrder: 'DO',
    DeliveryOrderBales: 'DB',
    ProdOrder: 'PR',
    PurchaseOrder: 'PO',
    SalesOrder: 'SO',
    UsersR: 'R',
    UsersL2: 'L2',
    UsersBuyer: 'B',
    UsersL1: 'L1',
  },
  response: {
    success_created: 'Success',
    failed_created: 'Failed',
  },
  route: {
    attachments: 'attachments',
    receiving_material: 'receiving_material',
    production_order: 'production_order',
    production_order_cart: 'production_order_cart',
    bales_pressing: 'bales_pressing',
    delivery_order: 'delivery_order',
    generate_number: 'generate_number',
    master_goods_cart: 'master_goods_cart',
    users: 'users',
    auth: 'auth',
    district: 'district',
    regency: 'regency',
    province: 'province',
    department: 'department',
    job: 'job',
    job_level: 'job_level',
    uom: 'uom',
    role_user: 'role_user',
    material_goods: 'material_goods',
    feedstock_type: 'feedstock_type',
    purchase_order: 'purchase_order',
    sales_order: 'sales_order',
    transaction_cart: 'transaction_cart',
    transaction: 'transaction',
    tracking: 'tracking',
    indonesia: 'indonesia',
    dashboard: 'dashboard',
    kpi: 'kpi',
  },
};

module.exports = strings;
